# Content Based Recommendation System

# Q1 Read the Dataset movies_metadata.csv

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

#pd.set_option('display.max_columns', 100)
cb_df = pd.read_csv('movies_metadata.csv')
cb_df.head()

C:\Users\5034100\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [2]:
cb_df.shape

(45466, 24)

# Q2 Create a new column with name 'description' combining `'overview' and 'tagline'` columns in the given dataset

In [3]:
cb_df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [4]:
# Lamdba function is created to concatenate the values to check the null values in each column
# ensuring only column with null in both are null - 954 records with null values in both columns
cb_df['description']=''
cb_df['description']=cb_df.apply(lambda x: cb_df['overview'] if cb_df['tagline'].isnull else ( cb_df['overview'] if cb_df['overview'].isnull else cb_df['overview']+cb_df['tagline']) )

In [5]:
cb_df[['overview','tagline','description']].head()
#Note: In "overview" column there are 5 records observed with "space" (not null) and are considered as it is for this lab excersise.

,overview,tagline,description
0,"Led by Woody, Andy's toys live happily in his ...",NaN,"Led by Woody, Andy's toys live happily in his ..."
1,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...
2,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...
3,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom..."
4,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...

In [6]:
# New column "description" has in total 954 Null values
cb_df['description'].isnull().sum()

954

# Q3  Lets drop the null values in `description` column

In [7]:
cb_df.shape

(45466, 25)

In [8]:
# Dropping null values in descrition column
cb_df.dropna(axis=0, subset=['description'],inplace=True)

In [9]:
cb_df.isnull().sum()

adult                        0
belongs_to_collection    40077
budget                       0
genres                       0
homepage                 36747
id                           0
imdb_id                     15
original_language           10
original_title               0
overview                     0
popularity                   5
poster_path                346
production_companies         3
production_countries         3
release_date                74
revenue                      6
runtime                      6
spoken_languages             6
status                      71
tagline                  24108
title                        6
video                        6
vote_average                 6
vote_count                   6
description                  0
dtype: int64

# Q4 Keep the first occurance and drop duplicates of each title in column `title`

In [10]:
#drop_duplicates functions used to drop duplicates of each title in column title.
cb_df.drop_duplicates(subset=['title'],inplace=True)

In [11]:
cb_df.shape
# 3140 duplicates removed (Orfginal : 44512 records New records: 41372)

(41372, 25)

# Q5   As we might have dropped a few rows with duplicate `title` in above step, just reset the index [make sure you are not adding any new column to the dataframe while doing reset index]

In [12]:
# Restting index
cb_df.reset_index(drop=True,inplace=True)

In [13]:
cb_df.shape

(41372, 25)

In [14]:
cb_df.set_index('title', inplace = True)
cb_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,video,vote_average,vote_count,description
title,,,,,,,,,,,,,,,,,,,,,
Toy Story,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,False,7.7,5415.0,"Led by Woody, Andy's toys live happily in his ..."
Jumanji,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,False,6.9,2413.0,When siblings Judy and Peter discover an encha...
Grumpier Old Men,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,False,6.5,92.0,A family wedding reignites the ancient feud be...
Waiting to Exhale,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,False,6.1,34.0,"Cheated on, mistreated and stepped on, the wom..."
Father of the Bride Part II,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,False,5.7,173.0,Just when George Banks has recovered from his ...

# Q6    Generate tf matrix using countvectorizer

Hint:
tf = CountVectorizer()

In [15]:
# instantiating and generating the count matrix
tf = CountVectorizer()
count_matrix = tf.fit_transform(cb_df['description'])

# creating a Series for the movie titles so they are associated to an ordered numerical
# list is used later to match the indexes
indices = pd.Series(cb_df.index)
indices[:5]

0                      Toy Story
1                        Jumanji
2               Grumpier Old Men
3              Waiting to Exhale
4    Father of the Bride Part II
Name: title, dtype: object

In [16]:
count_matrix

<41372x74018 sparse matrix of type '<class 'numpy.int64'>'
	with 1753423 stored elements in Compressed Sparse Row format>

In [17]:
print(count_matrix[0,:])

  (0, 17339)	1
  (0, 4318)	1
  (0, 51937)	1
  (0, 65683)	1
  (0, 37100)	1
  (0, 21361)	1
  (0, 19163)	1
  (0, 47366)	1
  (0, 65057)	2
  (0, 24355)	1
  (0, 3041)	1
  (0, 58036)	1
  (0, 12209)	1
  (0, 71025)	1
  (0, 9625)	1
  (0, 1837)	1
  (0, 49852)	1
  (0, 28544)	1
  (0, 49663)	1
  (0, 38462)	1
  (0, 46151)	1
  (0, 1797)	1
  (0, 57119)	1
  (0, 65037)	2
  (0, 46532)	1
  (0, 37755)	1
  (0, 9675)	3
  (0, 8901)	1
  (0, 7350)	1
  (0, 68370)	1
  (0, 55480)	1
  (0, 29371)	2
  (0, 31181)	2
  (0, 28043)	1
  (0, 38066)	1
  (0, 66235)	1
  (0, 3107)	3
  (0, 71709)	3
  (0, 9690)	1
  (0, 37157)	1

In [18]:
type(count_matrix)

scipy.sparse.csr.csr_matrix

In [19]:
tf.vocabulary_

{'led': 37157,
 'by': 9690,
 'woody': 71709,
 'andy': 3107,
 'toys': 66235,
 'live': 38066,
 'happily': 28043,
 'in': 31181,
 'his': 29371,
 'room': 55480,
 'until': 68370,
 'birthday': 7350,
 'brings': 8901,
 'buzz': 9675,
 'lightyear': 37755,
 'onto': 46532,
 'the': 65037,
 'scene': 57119,
 'afraid': 1797,
 'of': 46151,
 'losing': 38462,
 'place': 49663,
 'heart': 28544,
 'plots': 49852,
 'against': 1837,
 'but': 9625,
 'when': 71025,
 'circumstances': 12209,
 'separate': 58036,
 'and': 3041,
 'from': 24355,
 'their': 65057,
 'owner': 47366,
 'duo': 19163,
 'eventually': 21361,
 'learns': 37100,
 'to': 65683,
 'put': 51937,
 'aside': 4318,
 'differences': 17339,
 'siblings': 59221,
 'judy': 33819,
 'peter': 48985,
 'discover': 17680,
 'an': 2945,
 'enchanted': 20405,
 'board': 7811,
 'game': 24908,
 'that': 65022,
 'opens': 46580,
 'door': 18464,
 'magical': 39228,
 'world': 71772,
 'they': 65144,
 'unwittingly': 68421,
 'invite': 32385,
 'alan': 2208,
 'adult': 1631,
 'who': 71138,
 'been': 6413,
 'trapped': 66481,
 'inside': 31879,
 'for': 23681,
 '26': 579,
 'years': 72257,
 'into': 32260,
 'living': 38085,
 'only': 46509,
 'hope': 29788,
 'freedom': 24153,
 'is': 32557,
 'finish': 23009,
 'which': 71039,
 'proves': 51491,
 'risky': 55028,
 'as': 4226,
 'all': 2433,
 'three': 65280,
 'find': 22979,
 'themselves': 65076,
 'running': 55892,
 'giant': 25702,
 'rhinoceroses': 54743,
 'evil': 21405,
 'monkeys': 42896,
 'other': 47009,
 'terrifying': 64858,
 'creatures': 14643,
 'family': 22140,
 'wedding': 70758,
 'reignites': 53716,
 'ancient': 3037,
 'feud': 22738,
 'between': 6986,
 'next': 44990,
 'neighbors': 44714,
 'fishing': 23124,
 'buddies': 9255,
 'john': 33559,
 'max': 40709,
 'meanwhile': 41062,
 'sultry': 62932,
 'italian': 32687,
 'divorcÃ©e': 18092,
 'restaurant': 54412,
 'at': 4539,
 'local': 38161,
 'bait': 5430,
 'shop': 58976,
 'alarming': 2214,
 'locals': 38167,
 'worry': 71796,
 'she': 58591,
 'll': 38109,
 'scare': 57069,
 'fish': 23108,
 'away': 5036,
 'less': 37445,
 'interested': 32105,
 'seafood': 57554,
 'than': 64995,
 'cooking': 14022,
 'up': 68433,
 'hot': 29943,
 'time': 65522,
 'with': 71521,
 'cheated': 11518,
 'on': 46464,
 'mistreated': 42441,
 'stepped': 61963,
 'women': 71649,
 'are': 3877,
 'holding': 29550,
 'breath': 8726,
 'waiting': 70307,
 'elusive': 20117,
 'good': 26322,
 'man': 39648,
 'break': 8700,
 'string': 62436,
 'stellar': 61930,
 'lovers': 38551,
 'friends': 24292,
 'confidants': 13512,
 'vannah': 68945,
 'bernie': 6847,
 'glo': 26037,
 'robin': 55187,
 'talk': 64058,
 'it': 32683,
 'out': 47070,
 'determined': 16972,
 'better': 6973,
 'way': 70658,
 'breathe': 8728,
 'just': 33973,
 'george': 25488,
 'banks': 5687,
 'has': 28254,
 'recovered': 53349,
 'daughter': 15800,
 'he': 28480,
 'receives': 53222,
 'news': 44959,
 'pregnant': 50762,
 'wife': 71228,
 'nina': 45213,
 'expecting': 21655,
 'too': 65921,
 'was': 70543,
 'planning': 49713,
 'selling': 57888,
 'home': 29610,
 'plan': 49695,
 'like': 37769,
 'will': 71303,
 'have': 28386,
 'change': 11276,
 'arrival': 4115,
 'both': 8332,
 'grandchild': 26616,
 'kid': 35026,
 'own': 47363,
 'obsessive': 45982,
 'master': 40458,
 'thief': 65159,
 'neil': 44723,
 'mccauley': 40837,
 'leads': 37055,
 'top': 65950,
 'notch': 45581,
 'crew': 14695,
 'various': 68991,
 'insane': 31843,
 'heists': 28725,
 'throughout': 65318,
 'los': 38455,
 'angeles': 3134,
 'while': 71043,
 'mentally': 41453,
 'unstable': 68326,
 'detective': 16954,
 'vincent': 69688,
 'hanna': 27987,
 'pursues': 51909,
 'him': 29265,
 'without': 71539,
 'rest': 54407,
 'each': 19397,
 'recognizes': 53290,
 'respects': 54384,
 'ability': 1034,
 'dedication': 16148,
 'even': 21349,
 'though': 65252,
 'aware': 5031,
 'cat': 10741,
 'mouse': 43385,
 'may': 40733,
 'end': 20455,
 'violence': 69740,
 'ugly': 67482,
 'duckling': 19026,
 'having': 28393,
 'undergone': 67797,
 'remarkable': 53919,
 'still': 62060,
 'harbors': 28072,
 'feelings': 22530,
 'her': 28906,
 'crush': 14954,
 'carefree': 10382,
 'playboy': 49767,
 'not': 45575,
 'before': 6443,
 'business': 9595,
 'focused': 23551,
 'brother': 9058,
 'something': 60654,
 'say': 56971,
 'about': 1075,
 'mischievous': 42330,
 'young': 72467,
 'boy': 8465,
 'tom': 65819,
 'sawyer': 56962,
 'witnesses': 71548,
 'murder': 43718,
 'deadly': 15910,
 'injun': 31746,
 'joe': 33528,
 'becomes': 6362,
 'huckleberry': 30123,
 'finn': 23025,
 'no': 45303,
 'future': 24654,
 'choose': 11901,
 'honoring': 29725,
 'friendship': 24293,
 'or': 46691,
 'oath': 45871,
 'because': 6340,
 'town': 66198,
 'alcoholic': 2268,
 'accused': 1269,
 'huck': 30121,
 'go': 26125,
 'through': 65317,
 'several': 58253,
 'adventures': 1656,
 'trying': 66951,
 'retrieve': 54536,
 'evidence': 21399,
 'international': 32155,
 'action': 1374,
 'superstar': 63116,
 'jean': 33168,
 'claude': 12369,
 'van': 68887,
 'damme': 15542,
 'teams': 64483,
 'powers': 50553,
 'boothe': 8182,
 'tension': 64757,
 'packed': 47457,
 'suspense': 63321,
 'thriller': 65291,
 'set': 58201,
 'back': 5249,
 'drop': 18903,
 'stanley': 61694,
 'cup': 15124,
 'portrays': 50348,
 'father': 22352,
 'whose': 71163,
 'suddenly': 62811,
 'taken': 64004,
 'during': 19204,
 'championship': 11252,
 'hockey': 29485,
 'captors': 10290,
 'demanding': 16481,
 'billion': 7223,
 'dollars': 18307,
 'frantically': 24072,
 'sets': 58215,
 'motion': 43287,
 'rescue': 54269,
 'abort': 1066,
 'impending': 31011,
 'explosion': 21728,
 'final': 22957,
 'buzzer': 9680,
 'james': 32959,
 'bond': 8051,
 'must': 43810,
 'unmask': 68138,
 'mysterious': 43931,
 'head': 28481,
 'janus': 33037,
 'syndicate': 63706,
 'prevent': 50945,
 'leader': 37050,
 'utilizing': 68642,
 'goldeneye': 26236,
 'weapons': 70712,
 'system': 63737,
 'inflict': 31596,
 'devastating': 17029,
 'revenge': 54599,
 'britain': 8926,
 'widowed': 71198,
 'president': 50877,
 'andrew': 3082,
 'shepherd': 58680,
 'one': 46480,
 'most': 43262,
 'powerful': 50541,
 'men': 41388,
 'can': 10089,
 'anything': 3510,
 'wants': 70454,
 'what': 70991,
 'covets': 14475,
 'sydney': 63639,
 'ellen': 20051,
 'wade': 70253,
 'washington': 70553,
 'lobbyist': 38146,
 'attempts': 4663,
 'courting': 14435,
 'spark': 60993,
 'wild': 71260,
 'rumors': 55866,
 'decimate': 16061,
 'approval': 3692,
 'ratings': 52909,
 'lawyer': 36993,
 'shows': 59087,
 'vampire': 68874,
 'doorstep': 18472,
 'falls': 22108,
 'prey': 50960,
 'charms': 11405,
 'joins': 33580,
 'search': 57581,
 'fresh': 24239,
 'blood': 7683,
 'enter': 20704,
 'dr': 18677,
 'helsing': 28817,
 'be': 6227,
 'able': 1043,
 'vanquish': 68949,
 'count': 14361,
 'outcast': 47083,
 'half': 27742,
 'wolf': 71611,
 'risks': 55027,
 'life': 37695,
 'epidemic': 20828,
 'ravaging': 52956,
 'nome': 45397,
 'alaska': 2217,
 'star': 61706,
 'cast': 10696,
 'this': 65198,
 'epic': 20823,
 'look': 38355,
 'american': 2803,
 'richard': 54799,
 'nixon': 45293,
 'carrying': 10561,
 'fate': 22345,
 'shoulders': 59039,
 'battling': 6137,
 'self': 57862,
 'destructive': 16932,
 'demands': 16482,
 'within': 71537,
 'spanning': 60982,
 'troubled': 66839,
 'boyhood': 8480,
 'california': 9931,
 'shocking': 58928,
 'watergate': 70606,
 'scandal': 57037,
 'would': 71825,
 'presidency': 50876,
 'morgan': 43118,
 'adams': 1426,
 'slave': 59920,
 'william': 71315,
 'shaw': 58581,
 'quest': 52171,
 'recover': 53348,
 'portions': 50330,
 'treasure': 66557,
 'map': 39919,
 'unfortunately': 67970,
 'portion': 50329,
 'held': 28737,
 'murderous': 43725,
 'uncle': 67703,
 'dawg': 15846,
 'skeptical': 59738,
 'leadership': 37053,
 'abilities': 1033,
 'so': 60401,
 'complete': 13280,
 'mutiny': 43858,
 'made': 39132,
 'yet': 72313,
 'more': 43102,
 'difficult': 17351,
 'efforts': 19725,
 'british': 8932,
 'crown': 14899,
 'pirate': 49542,
 'raids': 52494,
 'gambling': 24905,
 'paradise': 47833,
 'las': 36802,
 'vegas': 69125,
 'its': 32709,
 'dark': 15704,
 'mafia': 39196,
 'underbelly': 67774,
 'rich': 54798,
 'mr': 43458,
 'dashwood': 15775,
 'dies': 17319,
 'leaving': 37121,
 'second': 57643,
 'daughters': 15801,
 'poor': 50230,
 'rules': 55841,
 'inheritance': 31707,
 'two': 67331,
 'titular': 65662,
 'opposites': 46638,
 'ted': 64535,
 'bellhop': 6607,
 'first': 23099,
 'night': 45127,
 'job': 33498,
 'hotel': 29952,
 'very': 69399,
 'unusual': 68389,
 'guests': 27206,
 'some': 60643,
 'outrageous': 47150,
 'predicaments': 50719,
 'seems': 57743,
 'evening': 21350,
 'service': 58171,
 'serving': 58180,
 'unbelievable': 67654,
 'happening': 28037,
 'after': 1817,
 'another': 3343,
 'summoned': 62965,
 'ashram': 4306,
 'tibet': 65400,
 'ace': 1280,
 'finds': 22987,
 'himself': 29284,
 'perilous': 48769,
 'journey': 33726,
 'jungles': 33919,
 'africa': 1799,
 'shikaka': 58752,
 'missing': 42410,
 'sacred': 56168,
 'animal': 3202,
 'friendly': 24291,
 'wachati': 70237,
 'tribe': 66655,
 'accomplish': 1222,
 'princess': 51011,
 'prince': 51008,
 'warrior': 70526,
 'wachootoos': 70239,
 'if': 30697,
 'fails': 22015,
 'result': 54452,
 'vicious': 69488,
 'tribal': 66654,
 'war': 70456,
 'vengeful': 69211,
 'new': 44923,
 'york': 72424,
 'transit': 66414,
 'cop': 14066,
 'decides': 16059,
 'steal': 61864,
 'trainload': 66322,
 'subway': 62756,
 'fares': 22231,
 'foster': 23904,
 'fellow': 22582,
 'tries': 66689,
 'protect': 51435,
 'chili': 11774,
 'palmer': 47645,
 'miami': 41755,
 'mobster': 42597,
 'gets': 25607,
 'sent': 58001,
 'boss': 8305,
 'psychopathic': 51652,
 'bones': 8066,
 'barboni': 5777,
 'collect': 12886,
 'bad': 5312,
 'debt': 15992,
 'harry': 28202,
 'zimm': 72936,
 'hollywood': 29587,
 'producer': 51167,
 'specializes': 61055,
 'cheesy': 11570,
 'horror': 29870,
 'films': 22935,
 'meets': 41198,
 'leading': 37054,
 'lady': 36456,
 'romantic': 55408,
 'sparks': 61000,
 'fly': 23529,
 'pitching': 49600,
 'story': 62241,
 'movie': 43415,
 'idea': 30624,
 'being': 6522,
 'really': 53103,
 'aren': 3882,
 'different': 17340,
 'agoraphobic': 1926,
 'psychologist': 51645,
 'female': 22595,
 'work': 71748,
 'together': 65743,
 'take': 63995,
 'down': 18629,
 'serial': 58123,
 'killer': 35113,
 'copies': 14075,
 'killers': 35114,
 'past': 48163,
 'assassin': 4388,
 'robert': 55174,
 'rath': 52898,
 'arrives': 4119,
 'funeral': 24551,
 'kill': 35107,
 'prominent': 51288,
 'witness': 71546,
 'rival': 55069,
 'hired': 29342,
 'gun': 27319,
 'grisly': 26945,
 'results': 54455,
 'horrified': 29864,
 'innocent': 31794,
 'bystanders': 9721,
 'last': 36830,
 'then': 65078,
 'return': 54556,
 'civilian': 12256,
 'finding': 22984,
 'contract': 13895,
 'killing': 35118,
 'grows': 27051,
 'ever': 21363,
 'dangerous': 15598,
 'target': 64286,
 'marked': 40135,
 'harassed': 28059,
 'classmates': 12362,
 'won': 71652,
 'accept': 1176,
 'appearance': 3611,
 'shy': 59195,
 'known': 35512,
 'powder': 50532,
 'struggles': 62500,
 'fit': 23142,
 'cruel': 14921,
 'taunts': 64409,
 'stop': 62198,
 'displays': 17879,
 'power': 50536,
 'allows': 2507,
 'do': 18148,
 'incredible': 31344,
 'things': 65173,
 'phenomenon': 49137,
 'changes': 11279,
 'lives': 38078,
 'those': 65250,
 'around': 4081,
 'ways': 70671,
 'never': 44909,
 'could': 14335,
 'imagined': 30885,
 'ben': 6663,
 'sanderson': 56570,
 'screenwriter': 57457,
 'lost': 38465,
 'everything': 21387,
 'drinking': 18869,
 'drink': 18866,
 'death': 15943,
 'there': 65110,
 'forms': 23819,
 'uneasy': 67903,
 'non': 45411,
 'interference': 32115,
 'pact': 47468,
 'prostitute': 51419,
 'sera': 58087,
 'iago': 30552,
 'pretends': 50921,
 'friend': 24287,
 'othello': 47008,
 'order': 46742,
 'manipulate': 39791,
 'serve': 58165,
 'film': 22908,
 'version': 69378,
 'shakespeare': 58410,
 'classic': 12349,
 'waxing': 70653,
 'nostalgic': 45566,
 'bittersweet': 7397,
 'passage': 48129,
 'childhood': 11759,
 'puberty': 51686,
 'tender': 64715,
 'coming': 13076,
 'age': 1854,
 'tale': 64039,
 'four': 23940,
 'girlfriends': 25875,
 'teeny': 64560,
 'chrissy': 11963,
 'samantha': 56478,
 'roberta': 55175,
 'recall': 53203,
 'summer': 62952,
 '1970': 406,
 'walk': 70359,
 'memory': 41385,
 'lane': 36667,
 'reconcile': 53307,
 'experiences': 21674,
 'boys': 8488,
 'secrets': 57663,
 'bullies': 9361,
 'adaptation': 1436,
 'jane': 32982,
 'austen': 4831,
 'novel': 45637,
 'follows': 23603,
 'anne': 3277,
 'elliot': 20060,
 'financially': 22970,
 'aristocratic': 3953,
 'persuaded': 48913,
 'engagement': 20535,
 'frederick': 24136,
 'wentworth': 70899,
 'sea': 57542,
 'captain': 10277,
 'meager': 41041,
 'means': 41059,
 'later': 36848,
 'money': 42855,
 'troubles': 66843,
 'force': 23695,
 'rent': 54068,
 'estate': 21146,
 'admiral': 1552,
 'croft': 14815,
 'again': 1836,
 'thrown': 65328,
 'company': 13211,
 'now': 45665,
 'successful': 62768,
 'perhaps': 48761,
 'love': 38528,
 'scientist': 57324,
 'surrealist': 63250,
 'society': 60454,
 'kidnaps': 35047,
 'children': 11767,
 'dreams': 18801,
 'hoping': 29802,
 'slow': 60068,
 'aging': 1892,
 'process': 51126,
 'provincial': 51502,
 'related': 53814,
 'shanghai': 58472,
 'crime': 14723,
 'recruited': 53364,
 'cosmopolitan': 14283,
 '1930s': 363,
 'servant': 58163,
 'ganglord': 24953,
 'mistress': 42444,
 'former': 23813,
 'marine': 40091,
 'louanne': 38484,
 'johnson': 33569,
 'lands': 36659,
 'gig': 25738,
 'teaching': 64472,
 'pilot': 49435,
 'program': 51228,
 'bright': 8873,
 'underachieving': 67770,
 'teens': 64558,
 'notorious': 45607,
 'inner': 31785,
 'city': 12246,
 'high': 29174,
 'school': 57246,
 'terrible': 64851,
 'day': 15856,
 'throw': 65321,
 'decorum': 16120,
 'wind': 71360,
 'returns': 54560,
 'classroom': 12363,
 'does': 18238,
 'armed': 4013,
 'nonsense': 45438,
 'attitude': 4690,
 'informed': 31620,
 'military': 42019,
 'training': 66321,
 'fearless': 22463,
 'determination': 16970,
 'students': 62531,
 'matter': 40626,
 'cost': 14291,
 'year': 72247,
 '2035': 484,
 'convict': 13988,
 'cole': 12848,
 'reluctantly': 53900,
 'volunteers': 70048,
 'origin': 46821,
 'virus': 69801,
 'wiped': 71463,
 'nearly': 44573,
 'earth': 19453,
 'population': 50280,
 'forced': 23697,
 'survivors': 63287,
 'underground': 67803,
 'communities': 13191,
 'mistakenly': 42431,
 '1990': 429,
 'instead': 31949,
 '1996': 436,
 'arrested': 4109,
 'locked': 38181,
 'mental': 41450,
 'hospital': 29917,
 'psychiatrist': 51625,
 'kathryn': 34525,
 'railly': 52503,
 'patient': 48232,
 'jeffrey': 33221,
 'goines': 26221,
 'son': 60681,
 'famous': 22144,
 'expert': 21685,
 'hold': 29546,
 'key': 34902,
 'rogue': 55311,
 'group': 27033,
 'army': 4044,
 '12': 61,
 'thought': 65253,
 'responsible': 54401,
 'unleashing': 68107,
 'disease': 17713,
 'babe': 5199,
 'little': 38051,
 'pig': 49380,
 'doesn': 18239,
 'quite': 52254,
 'know': 35502,
 'bunch': 9407,
 'odd': 46096,
 'ferdinand': 22638,
 'duck': 19022,
 'thinks': 65179,
 'rooster': 55497,
 'dog': 18242,
 'calls': 9968,
 'mom': 42794,
 'realizes': 53101,
 'makings': 39456,
 'become': 6361,
 'greatest': 26757,
 'sheep': 58612,
 'farmer': 22256,
 'hogget': 29516,
 'knows': 35515,
 'help': 28803,
 'dogs': 18266,
 'relationship': 53820,
 'painter': 47547,
 'dora': 18488,
 'carrington': 10550,
 'author': 4854,
 'lytton': 38932,
 'strachey': 62265,
 'england': 20554,
 'cottages': 14319,
 'countryside': 14391,
 'although': 2625,
 'platonic': 49751,
 'due': 19045,
 'homosexuality': 29671,
 'nevertheless': 44916,
 'deep': 16170,
 'complicated': 13294,
 'did': 17291,
 'develop': 17037,
 'physical': 49251,
 'soldier': 60561,
 'ralph': 52616,
 'partridge': 48083,
 'welcome': 70846,
 'remained': 53910,
 'somewhat': 60660,
 'much': 43479,
 'lifestyle': 37717,
 'sexual': 58311,
 'orientation': 46816,
 'fact': 21966,
 'conscientious': 13673,
 'objector': 45921,
 'justice': 33977,
 'drama': 18733,
 'based': 5986,
 'true': 66900,
 'row': 55694,
 'days': 15868,
 'strong': 62475,
 'nun': 45743,
 'teaches': 64471,
 'forgiveness': 23783,
 'gives': 25922,
 'spirituality': 61228,
 'accompanies': 1215,
 'execution': 21547,
 'susan': 63295,
 'sarandon': 56739,
 'oscar': 46930,
 'best': 6925,
 'actress': 1392,
 'convincing': 13997,
 'portrayal': 50344,
 'sister': 59627,
 'helen': 28742,
 'prejean': 50768,
 'russian': 55936,
 'thomas': 65204,
 'minton': 42228,
 'travels': 66522,
 'passenger': 48139,
 'freighter': 24197,
 'close': 12564,
 'ellis': 20063,
 'island': 32622,
 'off': 46154,
 'thus': 65372,
 'starts': 61774,
 'america': 2801,
 'same': 56491,
 'immigrants': 30944,
 'times': 65535,
 'searching': 57585,
 'ancestors': 3022,
 'had': 27617,
 'emigrated': 20256,
 'decades': 16013,
 'ago': 1915,
 'once': 46468,
 'letter': 37485,
 'sample': 56522,
 'profession': 51186,
 '3d': 659,
 'photography': 49236,
 'relative': 53822,
 'traces': 66246,
 'counter': 14364,
 'checking': 11539,
 'old': 46334,
 'photographs': 49235,
 'using': 68601,
 'antique': 3445,
 'viewer': 69576,
 'places': 49668,
 'how': 30043,
 'today': 65720,
 'audience': 4741,
 'see': 57716,
 'big': 7151,
 'apple': 3633,
 'well': 70855,
 'identical': 30641,
 'olds': 46343,
 'backgrounds': 5267,
 'orphaned': 46881,
 'amanda': 2705,
 'wealthy': 70705,
 'alyssa': 2677,
 'meet': 41194,
 'camp': 10054,
 'decide': 16055,
 'switch': 63585,
 'play': 49764,
 'matchmaker': 40515,
 'dad': 15400,
 'roger': 55306,
 'kind': 35174,
 'social': 60438,
 'worker': 71754,
 'cares': 10396,
 'shallow': 58424,
 'socially': 60450,
 'cher': 11626,
 'beverly': 6996,
 'hills': 29257,
 'pecking': 48439,
 'scale': 57010,
 'seeing': 57728,
 'herself': 29025,
 'coaxes': 12685,
 'teachers': 64470,
 'dating': 15792,
 'emboldened': 20217,
 'success': 62766,
 'give': 25917,
 'hopelessly': 29795,
 'klutzy': 35437,
 'student': 62530,
 'tai': 63922,
 'makeover': 39440,
 'popular': 50271,
 'disapproving': 17598,
 'ex': 21446,
 'stepbrother': 61945,
 'right': 54893,
 'misguided': 42367,
 'south': 60889,
 'african': 1801,
 'preacher': 50664,
 'goes': 26201,
 'wayward': 70675,
 'committed': 13155,
 'transplanted': 66450,
 'setting': 58222,
 'depicts': 16681,
 'heist': 28724,
 'bills': 7227,
 'retired': 54511,
 'circulation': 12205,
 'destined': 16915,
 'government': 26503,
 'burn': 9519,
 'however': 30052,
 ...}

# Q7  Create cosine similarity matrix

In [20]:
# generating the cosine similarity matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)
cosine_sim

array([[1.        , 0.18553901, 0.19482163, ..., 0.19474521, 0.32046644,
        0.27820744],
       [0.18553901, 1.        , 0.24419315, ..., 0.13076645, 0.36358853,
        0.30076282],
       [0.19482163, 0.24419315, 1.        , ..., 0.0549235 , 0.45813487,
        0.38446453],
       ...,
       [0.19474521, 0.13076645, 0.0549235 , ..., 1.        , 0.18692048,
        0.08823529],
       [0.32046644, 0.36358853, 0.45813487, ..., 0.18692048, 1.        ,
        0.59580903],
       [0.27820744, 0.30076282, 0.38446453, ..., 0.08823529, 0.59580903,
        1.        ]])

# Q8  Write a function with name `recommend` which takes `title` as argument and returns a list of 10 recommended title names in the output based on the above cosine similarities

Hint:

titles = df['title'] <br>
indices = pd.Series(df.index, index=df['title']) <br>

def recommend(title): <br>
    idx = indices[title] <br>
    sim_scores = list(enumerate(cosine_similarities[idx])) <br>
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True) <br>
    sim_scores = sim_scores[1:31] <br>
    movie_indices = [i[0] for i in sim_scores] <br>
    return titles.iloc[movie_indices] <br>

In [29]:
cb_df_temp = cb_df.reset_index()
titles = cb_df_temp['title']
indices = pd.Series(cb_df_temp.index, index=cb_df_temp['title'])

In [30]:
cb_df_temp.head()

,title,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,release_date,revenue,runtime,spoken_languages,status,tagline,video,vote_average,vote_count,description
0,Toy Story,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,False,7.7,5415.0,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,False,6.9,2413.0,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,False,6.5,92.0,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,False,6.1,34.0,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,False,5.7,173.0,Just when George Banks has recovered from his ...

In [31]:
def recommend(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    movie_indices = [i[0] for i in sim_scores]

    return titles.iloc[movie_indices]

# Q9 Give the recommendations from above functions for movies `The Godfather` and `The Dark Knight Rises`

In [32]:
recommend('The Godfather')

16350                                     The Tree of Life
40138                     The Godfather Trilogy: 1972-1990
22401                                       Largo Winch II
21768                               The Legend of Hercules
40993                                  Kites Over Helsinki
1656                               The Replacement Killers
9672                                                Wilson
40428                                      The Toth Family
32931               In girum imus nocte et consumimur igni
21390                                        I Saw the Sun
26914                 The Yakuza Papers, Vol. 3: Proxy War
15796                                               Kismet
36520                                           I Was Here
11575                                              Abraham
39969                                The Stroller Strategy
32188                                          Dirty Hands
8359                                           Spider Baby
13229    Ranma Â½: The Movie 1, Big Trouble in Nekonron,...
29290                                             Eadweard
35883                                      Angels One Five
4498                                          Left Luggage
19949                                   Perfumed Nightmare
31294                                    Pope John Paul II
6899                                               The Men
6228                                                Manito
10246                    The Bird with the Crystal Plumage
15052                                         Urban Menace
16844                      The Messengers 2: The Scarecrow
10439                                           Free Money
19732                                        The Tenth Man
Name: title, dtype: object

In [33]:
recommend('The Dark Knight Rises')

30605                                    The Dark Hour
40283                                           Blame!
29403                                      Pony Excess
11083    When the Levees Broke: A Requiem in Four Acts
30080                                       The Angrez
8679            Common Threads: Stories from the Quilt
25808                                     The Distance
27159                       The Postman's White Nights
18532                                  The Rusty Knife
25325                            Project: Shadowchaser
28127                                   The Golden Bat
20570                              A Cadaver Christmas
22168                       How to Train Your Dragon 2
12041                                  The Dark Knight
21617                               Threads of Destiny
34213                                 Eye of the Eagle
36958         The Work and the Glory II: American Zion
17778                                      Pale Cocoon
33899                                        Schoffies
29515                       Lissi and the Wild Emperor
22545                                        Kummeli V
36896                               Wind from the East
17508                                        14 Blades
5437                                          On Guard
7145                 The Rolling Stones: Gimme Shelter
18079                                      Outer Space
21158                                    Bounty Killer
23829                              House of the Dead 2
24277                                 The Hire: Ticker
15526                             The Human Experience
Name: title, dtype: object

# Popularity Based Recommendation System

### About Dataset

Anonymous Ratings on jokes.

1. Ratings are real values ranging from -10.00 to +10.00 (the value "99" corresponds to "null" = "not rated").

2. One row per user

3. The first column gives the number of jokes rated by that user. The next 100 columns give the ratings for jokes 01 - 100.

# Q10 Read the dataset(jokes.csv)

Take care about the header in read_csv() as there are no column names given in the dataset.

In [35]:
j_df = pd.read_csv('jokes.csv',header=None, skiprows=1)
j_df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,74,-7.82,8.79,-9.66,-8.16,-7.52,-8.50,-9.85,4.17,-8.98,...,2.82,99.00,99.00,99.00,99.00,99.00,-5.63,99.00,99.00,99.00
1,100,4.08,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,...,2.82,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
2,49,99.00,99.00,99.00,99.00,9.03,9.27,9.03,9.27,99.00,...,99.00,99.00,99.00,9.08,99.00,99.00,99.00,99.00,99.00,99.00
3,48,99.00,8.35,99.00,99.00,1.80,8.16,-2.82,6.21,99.00,...,99.00,99.00,99.00,0.53,99.00,99.00,99.00,99.00,99.00,99.00
4,91,8.50,4.61,-4.17,-5.39,1.36,1.60,7.04,4.61,-0.44,...,5.19,5.58,4.27,5.19,5.73,1.55,3.11,6.55,1.80,1.60

# Q11 Consider `ratings` named dataframe with only first 200 rows and all columns from 1(first column is 0) of dataset

In [36]:
ratings=j_df.iloc[:200,1:]
ratings

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
0,-7.82,8.79,-9.66,-8.16,-7.52,-8.50,-9.85,4.17,-8.98,-4.76,...,2.82,99.00,99.00,99.00,99.00,99.00,-5.63,99.00,99.00,99.00
1,4.08,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,9.22,...,2.82,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
2,99.00,99.00,99.00,99.00,9.03,9.27,9.03,9.27,99.00,99.00,...,99.00,99.00,99.00,9.08,99.00,99.00,99.00,99.00,99.00,99.00
3,99.00,8.35,99.00,99.00,1.80,8.16,-2.82,6.21,99.00,1.84,...,99.00,99.00,99.00,0.53,99.00,99.00,99.00,99.00,99.00,99.00
4,8.50,4.61,-4.17,-5.39,1.36,1.60,7.04,4.61,-0.44,5.73,...,5.19,5.58,4.27,5.19,5.73,1.55,3.11,6.55,1.80,1.60
5,-6.17,-3.54,0.44,-8.50,-7.09,-4.32,-8.69,-0.87,-6.65,-1.80,...,-3.54,-6.89,-0.68,-2.96,-2.18,-3.35,0.05,-9.08,-5.05,-3.45
6,99.00,99.00,99.00,99.00,8.59,-9.85,7.72,8.79,99.00,99.00,...,99.00,99.00,99.00,99.00,99.00,2.33,99.00,99.00,99.00,99.00
7,6.84,3.16,9.17,-6.21,-8.16,-1.70,9.27,1.41,-5.19,-4.42,...,7.23,-1.12,-0.10,-5.68,-3.16,-3.35,2.14,-0.05,1.31,0.00
8,-3.79,-3.54,-9.42,-6.89,-8.74,-0.29,-5.29,-8.93,-7.86,-1.60,...,4.37,-0.29,4.17,-0.29,-0.29,-0.29,-0.29,-0.29,-3.40,-4.95
9,3.01,5.15,5.15,3.01,6.41,5.15,8.93,2.52,3.01,8.16,...,99.00,4.47,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
10,-2.91,4.08,99.00,99.00,-5.73,99.00,2.48,-5.29,99.00,1.46,...,99.00,6.17,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
11,1.31,1.80,2.57,-2.38,0.73,0.73,-0.97,5.00,-7.23,-1.36,...,1.46,1.70,0.29,-3.30,3.45,5.44,4.08,2.48,4.51,4.66
12,99.00,99.00,99.00,99.00,5.87,99.00,5.58,0.53,99.00,7.14,...,99.00,99.00,7.52,99.00,99.00,99.00,99.00,99.00,99.00,99.00
13,9.22,9.27,9.22,8.30,7.43,0.44,3.50,8.16,5.97,8.98,...,8.11,-1.02,5.58,6.84,5.53,-5.92,8.20,8.98,-8.16,6.50
14,8.79,-5.78,6.02,3.69,7.77,-5.83,8.69,8.59,-5.92,7.52,...,2.72,-5.49,-8.59,8.69,-8.74,-3.01,8.30,-4.81,-2.38,-5.97
15,-3.50,1.55,2.33,-4.13,4.22,-2.28,-2.96,-0.49,2.91,1.99,...,3.11,1.70,0.24,-5.92,7.28,-1.36,3.74,2.82,-2.86,3.45
16,99.00,-9.27,99.00,99.00,-7.38,99.00,8.74,-6.31,99.00,2.33,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
17,3.16,7.62,3.79,8.25,4.22,7.62,2.43,0.97,0.53,0.83,...,0.83,5.68,3.69,0.19,0.29,3.59,0.49,8.06,0.49,7.62
18,4.22,3.64,99.00,99.00,2.52,99.00,4.13,-5.19,99.00,7.91,...,99.00,0.05,99.00,99.00,99.00,99.00,1.65,99.00,99.00,99.00
19,99.00,7.62,99.00,99.00,-8.64,2.43,8.93,-6.60,99.00,-9.47,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
20,2.57,-0.73,99.00,99.00,2.57,99.00,-4.22,2.67,99.00,-1.31,...,99.00,1.31,99.00,99.00,99.00,99.00,1.02,99.00,99.00,99.00
21,7.28,5.39,99.00,99.00,-4.22,99.00,8.93,3.50,99.00,6.12,...,99.00,-1.55,99.00,99.00,99.00,99.00,0.29,-4.61,99.00,99.00
22,2.72,4.17,6.50,-3.54,-3.30,2.86,7.04,4.95,6.17,8.93,...,99.00,-3.35,99.00,99.00,99.00,2.67,99.00,99.00,99.00,99.00
23,2.09,-7.57,4.17,-8.40,-6.31,5.34,-5.19,-5.05,-8.20,2.28,...,3.06,8.25,8.50,-9.51,8.45,8.16,7.82,8.50,8.35,-8.35
24,-3.93,-1.17,2.28,-0.44,-2.28,2.38,-3.93,4.51,-0.34,7.77,...,99.00,99.00,99.00,99.00,99.00,99.00,-1.50,-6.07,1.26,0.10
25,99.00,5.49,3.45,99.00,0.15,4.76,0.10,4.13,8.01,4.76,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
26,99.00,5.83,99.00,99.00,5.34,99.00,-4.47,2.18,-3.98,-3.25,...,99.00,99.00,4.47,99.00,99.00,99.00,99.00,99.00,99.00,99.00
27,0.49,0.15,0.15,-9.56,-9.76,-9.61,0.29,1.65,-4.61,-4.71,...,99.00,99.00,99.00,99.00,-0.97,99.00,99.00,99.00,99.00,99.00
28,99.00,99.00,99.00,99.00,-1.70,99.00,8.83,-1.89,99.00,99.00,...,0.24,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
29,99.00,4.08,99.00,99.00,5.87,99.00,0.44,2.28,99.00,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,99.00,99.00,99.00,99.00,4.27,99.00,4.81,-6.21,99.00,99.00,...,99.00,99.00,8.54,99.00,99.00,99.00,99.00,99.00,99.00,99.00
171,-4.56,-3.74,-2.67,99.00,-3.40,0.63,-5.34,0.44,5.34,4.08,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
172,99.00,99.00,99.00,99.00,4.37,99.00,-3.40,1.12,99.00,99.00,...,99.00,99.00,99.00,99.00,99.00,5.05,99.00,99.00,99.00,99.00
173,99.00,99.00,99.00,99.00,0.34,99.00,-1.65,0.83,99.00,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,-1.75,99.00,99.00,99.00
174,99.00,99.00,99.00,99.00,-4.32,99.00,3.45,4.37,99.00,5.73,...,99.00,99.00,99.00,99.00,7.14,99.00,99.00,99.00,99.00,99.00
175,-9.42,8.83,8.45,8.64,5.73,8.45,6.89,4.56,-9.42,-9.22,...,99.00,99.00,99.00,99.00,99.00,99.00,6.12,99.00,99.00,99.00
176,-3.54,-3.20,1.12,3.83,3.30,-2.33,-0.19,2.33,0.05,1.17,...,0.49,-4.22,1.50,1.02,-3.74,2.28,-1.65,2.09,-5.97,2.18
177,5.39,0.24,99.00,99.00,-6.55,99.00,-8.35,3.40,99.00,-4.42,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
178,99.00,99.00,99.00,99.00,4.13,8.40,8.54,3.59,99.00,4.47,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
179,4.42,-5.05,99.00,99.00,1.55,99.00,6.60,2.18,99.00,-4.22,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,-0.24,99.00,99.00
180,99.00,99.00,99.00,99.00,5.10,99.00,-6.31,1.21,99.00,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
181,5.44,0.49,99.00,99.00,-1.21,99.00,0.29,-0.63,99.00,5.53,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
182,99.00,-8.98,-9.66,99.00,-6.12,-7.91,-7.14,-5.24,99.00,-9.17,...,99.00,99.00,-2.33,99.00,99.00,99.00,99.00,99.00,99.00,99.00
183,8.30,8.20,4.95,99.00,0.78,99.00,5.78,-2.77,99.00,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
184,-8.16,-7.86,-1.02,99.00,0.34,99.00,0.49,-0.29,99.00,2.14,...,99.00,-8.74,99.00,-7.91,99.00,99.00,99.00,99.00,99.00,99.00
185,-2.86,-6.31,-4.90,1.89,3.01,8.11,4.81,1.60,-4.95,9.03,...,99.00,99.00,99.00,99.00,7.38,99.00,99.00,99.00,-6.65,7.18
186,-0.10,-5.68,1.50,-7.72,-7.91,1.12,-1.21,-3.74,-3.25,-1.89,...,99.00,99.00,-2.48,99.00,99.00,99.00,99.00,99.00,99.00,99.00
187,-6.31,-1.94,99.00,99.00,3.69,99.00,-4.08,3.06,99.00,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
188,99.00,99.00,99.00,99.00,8.16,0.15,4.03,7.67,99.00,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
189,99.00,-3.16,-3.45,99.00,2.96,-1.65,1.75,-4.42,99.00,-1.21,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
190,3.54,-6.70,-4.76,99.00,-8.16,99.00,1.84,-6.84,99.00,1.31,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
191,4.47,-0.19,1.55,-1.50,-4.42,4.22,-2.38,1.46,-0.39,-5.39,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
192,8.06,3.45,3.69,-1.36,3.93,2.14,2.77,0.34,2.52,3.69,...,5.78,5.05,5.68,-2.86,2.86,7.09,5.68,7.48,8.59,2.23
193,1.84,-2.23,5.49,5.49,4.37,9.22,9.08,5.78,-3.40,6.50,...,-5.29,-1.26,6.21,-2.96,-1.02,-6.17,4.90,9.22,8.16,6.80
194,-9.71,-8.25,-8.30,-2.62,-8.93,-0.05,2.18,4.47,1.21,2.38,...,4.61,-9.22,-6.50,3.25,2.62,1.99,8.74,-6.55,-0.53,-8.59
195,5.73,0.00,-0.58,1.75,2.86,7.23,2.04,-4.27,3.11,7.14,...,1.70,4.66,1.65,5.58,5.73,3.50,0.00,-2.04,2.91,1.84
196,1.80,5.39,8.06,-0.10,4.81,4.66,-7.09,-7.72,3.69,4.47,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
197,2.62,-3.79,-1.17,-0.44,-1.02,5.05,-3.69,2.18,3.30,-0.73,...,1.41,-2.52,-0.53,-1.89,1.17,-2.04,-1.17,-0.73,0.73,0.44
198,99.00,99.00,99.00,99.00,7.91,99.00,3.64,-1.89,99.00,99.00,...,2.96,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
199,5.58,-7.28,-4.56,2.67,7.38,2.18,2.14,2.23,5.58,-4.51,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00

In [37]:
ratings.shape

(200, 100)

# Q12 Change the column indices from 0 to 99

In [38]:
ratings.columns

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
             14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
             27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
             40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
             53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
             66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
             79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
             92,  93,  94,  95,  96,  97,  98,  99, 100],
           dtype='int64')

In [39]:
colnames=[]
colnames=list(range(100))
ratings.set_axis(colnames,axis=1,inplace=True)

In [40]:
ratings.head(1)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-7.82,8.79,-9.66,-8.16,-7.52,-8.5,-9.85,4.17,-8.98,-4.76,...,2.82,99.0,99.0,99.0,99.0,99.0,-5.63,99.0,99.0,99.0

# Q13 In the dataset, the null ratings are given as 99.00, so replace all 99.00s with 0
Hint: You can use `ratings.replace(<the given value>, <new value you wanted to change with>)`

In [41]:
ratings.replace(99,0,inplace=True)
ratings.head(1)
# Note: For rating i have considered zero as an observation ( not a NaN, so i have not given any treatment)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-7.82,8.79,-9.66,-8.16,-7.52,-8.5,-9.85,4.17,-8.98,-4.76,...,2.82,0.0,0.0,0.0,0.0,0.0,-5.63,0.0,0.0,0.0

# Q14 Normalize the ratings and save them in `ratings_diff` variable

In [42]:
ratings_diff = (ratings - ratings.mean())

In [43]:
ratings_diff

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-8.35005,8.1961,-9.89765,-7.459,-7.4821,-9.82005,-10.0215,4.2553,-8.9967,-5.6547,...,2.2574,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-6.385,-0.0937,-0.135,-0.5244
1,3.54995,-0.8839,6.12235,5.071,-2.3421,-10.98005,-0.9015,-5.2547,8.8633,8.3253,...,2.2574,-5.1251,-1.44585,7.2221,-0.77165,-2.55755,2.305,0.2463,-4.455,0.5456
2,-0.53005,-0.5939,-0.23765,0.701,9.0679,7.94995,8.8585,9.3553,-0.0167,-0.8947,...,-0.5626,-0.1751,-1.15585,8.4421,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
3,-0.53005,7.7561,-0.23765,0.701,1.8379,6.83995,-2.9915,6.2953,-0.0167,0.9453,...,-0.5626,-0.1751,-1.15585,-0.1079,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
4,7.96995,4.0161,-4.40765,-4.689,1.3979,0.27995,6.8685,4.6953,-0.4567,4.8353,...,4.6274,5.4049,3.11415,4.5521,5.14835,1.13245,2.355,6.4563,1.665,1.0756
5,-6.70005,-4.1339,0.20235,-7.799,-7.0521,-5.64005,-8.8615,-0.7847,-6.6667,-2.6947,...,-4.1026,-7.0651,-1.83585,-3.5979,-2.76165,-3.76755,-0.705,-9.1737,-5.185,-3.9744
6,-0.53005,-0.5939,-0.23765,0.701,8.6279,-11.17005,7.5485,8.8753,-0.0167,-0.8947,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,1.91245,-0.755,-0.0937,-0.135,-0.5244
7,6.30995,2.5661,8.93235,-5.509,-8.1221,-3.02005,9.0985,1.4953,-5.2067,-5.3147,...,6.6674,-1.2951,-1.25585,-6.3179,-3.74165,-3.76755,1.385,-0.1437,1.175,-0.5244
8,-4.32005,-4.1339,-9.65765,-6.189,-8.7021,-1.61005,-5.4615,-8.8447,-7.8767,-2.4947,...,3.8074,-0.4651,3.01415,-0.9279,-0.87165,-0.70755,-1.045,-0.3837,-3.535,-5.4744
9,2.47995,4.5561,4.91235,3.711,6.4479,3.82995,8.7585,2.6053,2.9933,7.2653,...,-0.5626,4.2949,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
10,-3.44005,3.4861,-0.23765,0.701,-5.6921,-1.32005,2.3085,-5.2047,-0.0167,0.5653,...,-0.5626,5.9949,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
11,0.77995,1.2061,2.33235,-1.679,0.7679,-0.59005,-1.1415,5.0853,-7.2467,-2.2547,...,0.8974,1.5249,-0.86585,-3.9379,2.86835,5.02245,3.325,2.3863,4.375,4.1356
12,-0.53005,-0.5939,-0.23765,0.701,5.9079,-1.32005,5.4085,0.6153,-0.0167,6.2453,...,-0.5626,-0.1751,6.36415,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
13,8.68995,8.6761,8.98235,9.001,7.4679,-0.88005,3.3285,8.2453,5.9533,8.0853,...,7.5474,-1.1951,4.42415,6.2021,4.94835,-6.33755,7.445,8.8863,-8.295,5.9756
14,8.25995,-6.3739,5.78235,4.391,7.8079,-7.15005,8.5185,8.6753,-5.9367,6.6253,...,2.1574,-5.6651,-9.74585,8.0521,-9.32165,-3.42755,7.545,-4.9037,-2.515,-6.4944
15,-4.03005,0.9561,2.09235,-3.429,4.2579,-3.60005,-3.1315,-0.4047,2.8933,1.0953,...,2.5474,1.5249,-0.91585,-6.5579,6.69835,-1.77755,2.985,2.7263,-2.995,2.9256
16,-0.53005,-9.8639,-0.23765,0.701,-7.3421,-1.32005,8.5685,-6.2247,-0.0167,1.4353,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
17,2.62995,7.0261,3.55235,8.951,4.2579,6.29995,2.2585,1.0553,0.5133,-0.0647,...,0.2674,5.5049,2.53415,-0.4479,-0.29165,3.17245,-0.265,7.9663,0.355,7.0956
18,3.68995,3.0461,-0.23765,0.701,2.5579,-1.32005,3.9585,-5.1047,-0.0167,7.0153,...,-0.5626,-0.1251,-1.15585,-0.6379,-0.58165,-0.41755,0.895,-0.0937,-0.135,-0.5244
19,-0.53005,7.0261,-0.23765,0.701,-8.6021,1.10995,8.7585,-6.5147,-0.0167,-10.3647,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
20,2.03995,-1.3239,-0.23765,0.701,2.6079,-1.32005,-4.3915,2.7553,-0.0167,-2.2047,...,-0.5626,1.1349,-1.15585,-0.6379,-0.58165,-0.41755,0.265,-0.0937,-0.135,-0.5244
21,6.74995,4.7961,-0.23765,0.701,-4.1821,-1.32005,8.7585,3.5853,-0.0167,5.2253,...,-0.5626,-1.7251,-1.15585,-0.6379,-0.58165,-0.41755,-0.465,-4.7037,-0.135,-0.5244
22,2.18995,3.5761,6.26235,-2.839,-3.2621,1.53995,6.8685,5.0353,6.1533,8.0353,...,-0.5626,-3.5251,-1.15585,-0.6379,-0.58165,2.25245,-0.755,-0.0937,-0.135,-0.5244
23,1.55995,-8.1639,3.93235,-7.699,-6.2721,4.01995,-5.3615,-4.9647,-8.2167,1.3853,...,2.4974,8.0749,7.34415,-10.1479,7.86835,7.74245,7.065,8.4063,8.215,-8.8744
24,-4.46005,-1.7639,2.04235,0.261,-2.2421,1.05995,-4.1015,4.5953,-0.3567,6.8753,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-2.255,-6.1637,1.125,-0.4244
25,-0.53005,4.8961,3.21235,0.701,0.1879,3.43995,-0.0715,4.2153,7.9933,3.8653,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
26,-0.53005,5.2361,-0.23765,0.701,5.3779,-1.32005,-4.6415,2.2653,-3.9967,-4.1447,...,-0.5626,-0.1751,3.31415,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
27,-0.04005,-0.4439,-0.08765,-8.859,-9.7221,-10.93005,0.1185,1.7353,-4.6267,-5.6047,...,-0.5626,-0.1751,-1.15585,-0.6379,-1.55165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
28,-0.53005,-0.5939,-0.23765,0.701,-1.6621,-1.32005,8.6585,-1.8047,-0.0167,-0.8947,...,-0.3226,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
29,-0.53005,3.4861,-0.23765,0.701,5.9079,-1.32005,0.2685,2.3653,-0.0167,-0.8947,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,-0.53005,-0.5939,-0.23765,0.701,4.3079,-1.32005,4.6385,-6.1247,-0.0167,-0.8947,...,-0.5626,-0.1751,7.38415,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
171,-5.09005,-4.3339,-2.90765,0.701,-3.3621,-0.69005,-5.5115,0.5253,5.3233,3.1853,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
172,-0.53005,-0.5939,-0.23765,0.701,4.4079,-1.32005,-3.5715,1.2053,-0.0167,-0.8947,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,4.63245,-0.755,-0.0937,-0.135,-0.5244
173,-0.53005,-0.5939,-0.23765,0.701,0.3779,-1.32005,-1.8215,0.9153,-0.0167,-0.8947,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-2.505,-0.0937,-0.135,-0.5244
174,-0.53005,-0.5939,-0.23765,0.701,-4.2821,-1.32005,3.2785,4.4553,-0.0167,4.8353,...,-0.5626,-0.1751,-1.15585,-0.6379,6.55835,-0.41755,-0.755,-0.0937,-0.135,-0.5244
175,-9.95005,8.2361,8.21235,9.341,5.7679,7.12995,6.7185,4.6453,-9.4367,-10.1147,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,5.365,-0.0937,-0.135,-0.5244
176,-4.07005,-3.7939,0.88235,4.531,3.3379,-3.65005,-0.3615,2.4153,0.0333,0.2753,...,-0.0726,-4.3951,0.34415,0.3821,-4.32165,1.86245,-2.405,1.9963,-6.105,1.6556
177,4.85995,-0.3539,-0.23765,0.701,-6.5121,-1.32005,-8.5215,3.4853,-0.0167,-5.3147,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
178,-0.53005,-0.5939,-0.23765,0.701,4.1679,7.07995,8.3685,3.6753,-0.0167,3.5753,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
179,3.88995,-5.6439,-0.23765,0.701,1.5879,-1.32005,6.4285,2.2653,-0.0167,-5.1147,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.3337,-0.135,-0.5244
180,-0.53005,-0.5939,-0.23765,0.701,5.1379,-1.32005,-6.4815,1.2953,-0.0167,-0.8947,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
181,4.90995,-0.1039,-0.23765,0.701,-1.1721,-1.32005,0.1185,-0.5447,-0.0167,4.6353,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
182,-0.53005,-9.5739,-9.89765,0.701,-6.0821,-9.23005,-7.3115,-5.1547,-0.0167,-10.0647,...,-0.5626,-0.1751,-3.48585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
183,7.76995,7.6061,4.71235,0.701,0.8179,-1.32005,5.6085,-2.6847,-0.0167,-0.8947,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
184,-8.69005,-8.4539,-1.25765,0.701,0.3779,-1.32005,0.3185,-0.2047,-0.0167,1.2453,...,-0.5626,-8.9151,-1.15585,-8.5479,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
185,-3.39005,-6.9039,-5.13765,2.591,3.0479,6.78995,4.6385,1.6853,-4.9667,8.1353,...,-0.5626,-0.1751,-1.15585,-0.6379,6.79835,-0.41755,-0.755,-0.0937,-6.785,6.6556
186,-0.63005,-6.2739,1.26235,-7.019,-7.8721,-0.20005,-1.3815,-3.6547,-3.2667,-2.7847,...,-0.5626,-0.1751,-3.63585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
187,-6.84005,-2.5339,-0.23765,0.701,3.7279,-1.32005,-4.2515,3.1453,-0.0167,-0.8947,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
188,-0.53005,-0.5939,-0.23765,0.701,8.1979,-1.17005,3.8585,7.7553,-0.0167,-0.8947,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
189,-0.53005,-3.7539,-3.68765,0.701,2.9979,-2.97005,1.5785,-4.3347,-0.0167,-2.1047,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
190,3.00995,-7.2939,-4.99765,0.701,-8.1221,-1.32005,1.6685,-6.7547,-0.0167,0.4153,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
191,3.93995,-0.7839,1.31235,-0.799,-4.3821,2.89995,-2.5515,1.5453,-0.4067,-6.2847,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
192,7.52995,2.8561,3.45235,-0.659,3.9679,0.81995,2.5985,0.4253,2.5033,2.7953,...,5.2174,4.8749,4.52415,-3.4979,2.27835,6.67245,4.925,7.3863,8.455,1.7056
193,1.30995,-2.8239,5.25235,6.191,4.4079,7.89995,8.9085,5.8653,-3.4167,5.6053,...,-5.8526,-1.4351,5.05415,-3.5979,-1.60165,-6.58755,4.145,9.1263,8.025,6.2756
194,-10.24005,-8.8439,-8.53765,-1.919,-8.8921,-1.37005,2.0085,4.5553,1.1933,1.4853,...,4.0474,-9.3951,-7.65585,2.6121,2.03835,1.57245,7.985,-6.6437,-0.665,-9.1144
195,5.19995,-0.5939,-0.81765,2.451,2.8979,5.90995,1.8685,-4.1847,3.0933,6.2453,...,1.1374,4.4849,0.49415,4.9421,5.14835,3.08245,-0.755,-2.1337,2.775,1.3156
196,1.26995,4.7961,7.82235,0.601,4.8479,3.33995,-7.2615,-7.6347,3.6733,3.5753,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
197,2.08995,-4.3839,-1.40765,0.261,-0.9821,3.72995,-3.8615,2.2653,3.2833,-1.6247,...,0.8474,-2.6951,-1.68585,-2.5279,0.58835,-2.45755,-1.925,-0.8237,0.595,-0.0844
198,-0.53005,-0.5939,-0.23765,0.701,7.9479,-1.32005,3.4685,-1.8047,-0.0167,-0.8947,...,2.3974,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244
199,5.04995,-7.8739,-4.79765,3.371,7.4179,0.85995,1.9685,2.3153,5.5633,-5.4047,...,-0.5626,-0.1751,-1.15585,-0.6379,-0.58165,-0.41755,-0.755,-0.0937,-0.135,-0.5244

### Popularity based recommendation system

# Q15  Find the mean for each column  in `ratings_diff` i.e, for each joke
Consider all the mean ratings and find the jokes with highest mean value and display the top 10 joke IDs.

In [44]:
ratings_diff.mean(axis=1).sort_values(ascending=False).head(10)

44     4.363708
94     4.249808
159    4.137508
86     3.789208
13     3.622908
73     3.561608
109    3.427608
46     3.387708
17     3.005208
36     2.785508
dtype: float64